export enum HybridColumnType {
  TEXT = 'TEXT',
  INTEGER = 'INTEGER',
  DECIMAL = 'DECIMAL',
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
  MINIO_IMAGE = 'MINIO_IMAGE',
  MINIO_FILE = 'MINIO_FILE'
}

export interface HybridMediaConstraints {
  maxImages: number;
  maxFileSizeBytes?: number;
  allowedMimeTypes?: string[];
}

export interface HybridMinioImageItem {
  key: string;
  url: string;
  expiresAt?: string;
  contentType?: string;
  sizeBytes?: number;
}

export interface HybridMinioImageValue {
  type: 'MINIO_IMAGE';
  items: HybridMinioImageItem[];
  maxImages?: number;
  constraints?: HybridMediaConstraints;
  count?: number;
}

export interface HybridColumnDefinition {
  name: string;
  displayName: string;
  labelKey?: string;
  type: HybridColumnType;
  required: boolean;
  unique?: boolean;
  hidden: boolean;
  primaryKey: boolean;
  autoGenerated: boolean;
  maxLength?: number;
  precision?: number;
  scale?: number;
  defaultValue?: string;
  displayOrder: number;
  validationRules?: Record<string, any>;
  semanticType?: string;
  metadata?: Record<string, any>;
  mediaConstraints?: HybridMediaConstraints;
}

export interface HybridTableSchema {
  id: number;
  tableName: string;
  displayName: string;
  domain: string;
  version: number;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
  columns: HybridColumnDefinition[];
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt?: Date;
}

export interface HybridSchema {
  entityType: string;
  displayName: string;
  columns: HybridColumnDefinition[];
}

export interface HybridSchemaConfigurationRequest {
  file: File;
  displayName: string;
  validateBeforeApply: boolean;
}

export interface HybridTemplateValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export interface HybridTemplateUploadProgress {
  uploadId: string;
  percentage: number;
  stage: string;
  message: string;
  timestamp: Date;
}

export interface HybridEntityRecord {
  id: string;
  [key: string]: any;
}

export type HybridEntity = HybridEntityRecord;

export interface HybridRawEntityDto {
  id: string;
  attributes: Record<string, any>;
}

export interface HybridPageResponse {
  content: HybridRawEntityDto[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
  first: boolean;
  last: boolean;
  columns?: HybridColumnDefinition[];
}
