export interface HybridEntityConfig {
  entityType: string;
  displayName: string;
}

export interface HybridColumnDefinition {
  name: string;
  displayName: string;
  type: HybridColumnType;
  required: boolean;
  primaryKey: boolean;
  autoGenerated: boolean;
  hidden: boolean;
  displayOrder: number;
  metadata?: Record<string, any>;
  semanticType?: string;
}

export enum HybridColumnType {
  TEXT = 'TEXT',
  INTEGER = 'INTEGER',
  DECIMAL = 'DECIMAL',
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
  MINIO_IMAGE = 'MINIO_IMAGE',
  MINIO_FILE = 'MINIO_FILE'
}

export interface HybridSchema {
  entityType: string;
  displayName: string;
  columns: HybridColumnDefinition[];
}

export interface HybridEntity {
  id: string;
  [key: string]: any;
}
