import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, map } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { HybridColumnDefinition, HybridColumnType, HybridEntity, HybridSchema } from '../models/hybrid-entity.model';

interface HybridSearchResponse {
  content: Array<Record<string, any>>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
  columns?: HybridColumnResponse[];
}

interface HybridColumnResponse {
  name: string;
  displayName: string;
  type: HybridColumnType;
  hidden: boolean;
  displayOrder: number;
  semanticType?: string;
  metadata?: Record<string, any>;
}

@Injectable({ providedIn: 'root' })
export class HybridDataService {
  private readonly http = inject(HttpClient);

  search(entityType: string, query: string | null, filters: HttpParams, includeSchema: boolean, page: number, size: number): Observable<{ records: HybridEntity[]; schema?: HybridSchema; total: number; page: number; size: number; }> {
    let params = new HttpParams()
      .set('page', String(page))
      .set('size', String(size))
      .set('includeSchema', String(includeSchema));
    if (query) {
      params = params.set('q', query);
    }
    filters.keys().forEach(key => {
      const values = filters.getAll(key) ?? [];
      values.forEach(value => { params = params.append(key, value); });
    });
    return this.http.get<HybridSearchResponse>(`${environment.apiBase}/api/hybrid/${entityType}`, { params }).pipe(
      map(resp => {
        const records: HybridEntity[] = (resp.content ?? []).map(row => {
          const id = row['id'] ?? '';
          const attrs = { ...row };
          delete attrs['id'];
          return { id, ...attrs } as HybridEntity;
        });
        let schema: HybridSchema | undefined;
        if (includeSchema && resp.columns) {
          const cols: HybridColumnDefinition[] = resp.columns.map(col => ({
            name: col.name,
            displayName: col.displayName,
            type: col.type,
            required: Boolean((col as any).required),
            primaryKey: false,
            autoGenerated: false,
            hidden: col.hidden,
            displayOrder: col.displayOrder,
            semanticType: col.semanticType,
            metadata: col.metadata
          }));
          schema = {
            entityType,
            displayName: entityType,
            columns: cols.sort((a, b) => a.displayOrder - b.displayOrder)
          };
        }
        return {
          records,
          schema,
          total: resp.totalElements ?? records.length,
          page: resp.page ?? 0,
          size: resp.size ?? size
        };
      })
    );
  }

  get(entityType: string, id: string): Observable<HybridEntity> {
    return this.http.get<Record<string, any>>(`${environment.apiBase}/api/hybrid/${entityType}/${id}`).pipe(
      map(response => {
        const attrs = { ...response };
        const entityId = attrs['id'] ?? id;
        delete attrs['id'];
        return { id: entityId, ...attrs } as HybridEntity;
      })
    );
  }

  create(entityType: string, payload: Record<string, any>): Observable<HybridEntity> {
    return this.http.post<Record<string, any>>(`${environment.apiBase}/api/hybrid/${entityType}`, { attributes: payload }).pipe(
      map(response => {
        const attrs = { ...response };
        const id = attrs['id'];
        delete attrs['id'];
        return { id, ...attrs } as HybridEntity;
      })
    );
  }

  update(entityType: string, id: string, payload: Record<string, any>): Observable<HybridEntity> {
    return this.http.put<Record<string, any>>(`${environment.apiBase}/api/hybrid/${entityType}/${id}`, { attributes: payload }).pipe(
      map(response => {
        const attrs = { ...response };
        const entityId = attrs['id'] ?? id;
        delete attrs['id'];
        return { id: entityId, ...attrs } as HybridEntity;
      })
    );
  }

  delete(entityType: string, id: string): Observable<void> {
    return this.http.delete<void>(`${environment.apiBase}/api/hybrid/${entityType}/${id}`);
  }
}
