export enum ColumnType {
  TEXT = 'TEXT',
  INTEGER = 'INTEGER',
  DECIMAL = 'DECIMAL',
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
  MINIO_IMAGE = 'MINIO_IMAGE',
  MINIO_FILE = 'MINIO_FILE'
}

export interface ColumnDefinition {
  name: string;
  displayName: string;
  labelKey: string;
  type: ColumnType;
  required: boolean;
  unique: boolean;
  hidden: boolean;
  primaryKey: boolean;
  autoGenerated: boolean;
  maxLength?: number;
  precision?: number;
  scale?: number;
  defaultValue?: string;
  displayOrder: number;
  validationRules?: Record<string, any>;
}

export interface ProductSchema {
  id: number;
  tableName: string;
  displayName: string;
  domain: string;
  version: number;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
  columns: ColumnDefinition[];
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt?: Date;
}

export interface SchemaConfigurationRequest {
  file: File;
  displayName: string;
  validateBeforeApply: boolean;
}

export interface TemplateValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export interface TemplateUploadProgress {
  uploadId: string;
  percentage: number;
  stage: string;
  message: string;
  timestamp: Date;
}
